// SPDX-License-Identifier: Apache-2.0
//
// FIDELITY.md emitter. Generates the Tools × Tier × Backing surface × Tests
// × Deviations table from a `TwinDefinition`. Per-tool fidelity metadata
// lives on `ToolSpec.fidelity` (optional); when missing, the row falls back
// to the manifest's `fidelity.default` tier and em-dash placeholders.

import type { TwinDefinition } from "./index.js";

export interface EmitFidelityOptions {
  /** ISO date (YYYY-MM-DD) embedded in "Last verified". Defaults to today. */
  lastVerified?: string;
  /** Optional trailing notes section appended after the table. */
  notes?: string;
}

export function emitFidelityMarkdown<TDb, TSeed, TDomain>(
  definition: TwinDefinition<TDb, TSeed, TDomain>,
  options: EmitFidelityOptions = {}
): string {
  const lastVerified = options.lastVerified ?? new Date().toISOString().slice(0, 10);
  const lines: string[] = [];

  lines.push(`# ${definition.id} Twin Fidelity`);
  lines.push("");
  lines.push(
    `Auto-generated by \`@pome-sh/sdk\` for twin \`${definition.id}\` v${definition.version}.`
  );
  lines.push("");
  lines.push(`Last verified: ${lastVerified}.`);
  lines.push("");
  lines.push("## MCP Tools");
  lines.push("");
  lines.push("| Tool | Backing surface | Tier | Tests | Known deviations |");
  lines.push("| --- | --- | --- | --- | --- |");

  for (const tool of definition.tools) {
    const fid = tool.fidelity ?? {};
    const tier = fid.tier ?? definition.fidelity.default;
    const surface = fid.backingSurface ?? "—";
    const tests = (fid.tests ?? []).length
      ? (fid.tests ?? []).map((t) => `\`${t}\``).join(", ")
      : "—";
    const deviations = (fid.deviations ?? "—").replace(/\r?\n/g, " ");
    lines.push(
      `| \`${tool.name}\` | ${surface} | ${tier} | ${tests} | ${deviations} |`
    );
  }

  if (options.notes) {
    lines.push("");
    lines.push("## Notes");
    lines.push("");
    lines.push(options.notes);
  }
  lines.push("");

  return lines.join("\n");
}
