// SPDX-License-Identifier: Apache-2.0
//
// F-754 export-surface guard. The `@pome-sh/shared-types` barrel is the public
// V1 contract; consumers (CLI, twins, pome-cloud) import runtime values by name
// from it. The topical-module split (F-754) must be provably zero-surface-change:
// if a re-export is dropped, renamed, or shadowed by an `export *` collision,
// the sorted key list below drifts and this test fails loud.
//
// The expected list is an explicit inline array (not a `.snap` file) so the
// public surface reads plainly in review. It was generated from the pre-refactor
// `main` build. When you intentionally add/remove an export, update this list in
// the same PR.

import { describe, expect, it } from "vitest";
import * as api from "../src/index.js";
// TYPE-surface guard: `Object.keys` only sees runtime values, so dropping an
// `export type` / `export interface` — or a whole type-only leaf re-export —
// would pass the runtime snapshot silently. This type-only import enumerates
// every `export type` / `export interface` that must remain on the barrel
// (grep-grounded from the pre-refactor index.ts, minus intentionally removed
// EvaluatorHooks / TraceUploadContext in 0.9.0). It is enforced when
// `npm run typecheck` compiles this test: a dropped or renamed type breaks
// the build.
import type {
  AcceptInviteRequest,
  AcceptInviteResponse,
  AgentResponse,
  ApiError,
  ApiErrorType,
  ApiKey,
  ApiKeyCreated,
  CreateAgentRequest,
  CreateEvalSessionResponse,
  CreateInviteRequest,
  CreateInviteResponse,
  CreateSessionRequest,
  CreateSessionResponse,
  CriterionDef,
  CriterionDefInput,
  FinalizeAcceptedResponse,
  FinalizeCompletedStatusResponse,
  FinalizeFailedStatusResponse,
  FinalizeFailureError,
  FinalizeInitialResponse,
  FinalizeQueuedStatusResponse,
  FinalizeRequest,
  FinalizeResponse,
  FinalizeRunningStatusResponse,
  FinalizeStatusResponse,
  FinalizeStatusUrl,
  GithubSeedState,
  MeResponse,
  PerTwinStateKeys,
  PersistedScenario,
  PersistedTask,
  PlanTier,
  Scenario,
  ScenarioConfig,
  SeedEnvelope,
  SeedState,
  Session,
  SessionPublic,
  SessionState,
  SlackSeedState,
  StateUploadUrlEntry,
  StateUploadUrlResponse,
  StripeSeedState,
  SubmitResultRequest,
  SubmitResultResponse,
  Task,
  TaskConfig,
  Team,
  TeamInvite,
  TeamMember,
  TeamRole,
  UsageResponse,
  User,
} from "../src/index.js";

// Referencing every imported type keeps the guard alive under
// noUnusedLocals-style settings; the tuple is never instantiated.
type _TypeSurfaceAssert = [
  AcceptInviteRequest,
  AcceptInviteResponse,
  AgentResponse,
  ApiError,
  ApiErrorType,
  ApiKey,
  ApiKeyCreated,
  CreateAgentRequest,
  CreateEvalSessionResponse,
  CreateInviteRequest,
  CreateInviteResponse,
  CreateSessionRequest,
  CreateSessionResponse,
  CriterionDef,
  CriterionDefInput,
  FinalizeAcceptedResponse,
  FinalizeCompletedStatusResponse,
  FinalizeFailedStatusResponse,
  FinalizeFailureError,
  FinalizeInitialResponse,
  FinalizeQueuedStatusResponse,
  FinalizeRequest,
  FinalizeResponse,
  FinalizeRunningStatusResponse,
  FinalizeStatusResponse,
  FinalizeStatusUrl,
  GithubSeedState,
  MeResponse,
  PerTwinStateKeys,
  PersistedScenario,
  PersistedTask,
  PlanTier,
  Scenario,
  ScenarioConfig,
  SeedEnvelope,
  SeedState,
  Session,
  SessionPublic,
  SessionState,
  SlackSeedState,
  StateUploadUrlEntry,
  StateUploadUrlResponse,
  StripeSeedState,
  SubmitResultRequest,
  SubmitResultResponse,
  Task,
  TaskConfig,
  Team,
  TeamInvite,
  TeamMember,
  TeamRole,
  UsageResponse,
  User,
];
// Compile-time anchor: exactly one tuple entry per guarded type. The literal
// type on the left fails to compile if an entry is added or removed above
// without updating the count.
const TYPE_SURFACE_SIZE: _TypeSurfaceAssert["length"] = 53;

// Runtime value exports (types are erased and cannot appear on `Object.keys`).
const EXPECTED_EXPORTS = [
  "CRITERION_KINDS",
  "ERROR_TYPE",
  "GEN_AI_AGENT_ID",
  "GEN_AI_AGENT_NAME",
  "GEN_AI_OPERATION_NAME",
  "GEN_AI_PROVIDER_NAME",
  "GEN_AI_REQUEST_MODEL",
  "GEN_AI_SYSTEM_DEPRECATED",
  "GEN_AI_TOOL_NAME",
  "GEN_AI_USAGE_COMPLETION_TOKENS_LEGACY",
  "GEN_AI_USAGE_INPUT_TOKENS",
  "GEN_AI_USAGE_OUTPUT_TOKENS",
  "GEN_AI_USAGE_PROMPT_TOKENS_LEGACY",
  "GITHUB_ACCESS_CONTROL_CATALOG",
  "GITHUB_ACCESS_CONTROL_CATEGORY_LABELS",
  "GITHUB_ACCESS_CONTROL_CATEGORY_ORDER",
  "HTTP_REQUEST_METHOD",
  "HTTP_RESPONSE_STATUS_CODE",
  "KNOWN_TWIN_IDS",
  "LEGACY_ATTR_NAMESPACE",
  "LEGACY_CRITERION_KIND_MAP",
  "LEGACY_ID_PREFIX",
  "LEGACY_SHIM_SEMCONV_VERSION",
  "LEGACY_TASK_VOCAB_KEY_MAP",
  "MOUNTED_TWINS",
  "OTEL_CORE_SEMCONV_VERSION",
  "OTEL_GENAI_SCHEMA_URL",
  "OTEL_GENAI_SCHEMA_VERSION",
  "OTEL_PROJECTION_KEYS",
  "OTEL_SPAN_KINDS",
  "OTEL_STATUS_CODES",
  "SERVER_ADDRESS",
  "SERVER_PORT",
  "UINT64_MAX",
  "URL_FULL",
  "URL_PATH",
  "acceptInviteRequestSchema",
  "acceptInviteResponseSchema",
  "agentResponseSchema",
  "apiErrorSchema",
  "apiErrorTypeSchema",
  "apiKeyCreatedSchema",
  "apiKeySchema",
  "canonicalSpanIdSchema",
  "canonicalTraceIdSchema",
  "compareUint64",
  "correlatorKindSchema",
  "createAgentRequestSchema",
  "createEvalSessionResponseSchema",
  "createInviteRequestSchema",
  "createInviteResponseSchema",
  "createSessionRequestSchema",
  "createSessionResponseSchema",
  "criterionDefSchema",
  "criterionKindSchema",
  "criterionResultSchema",
  "criterionSchema",
  "deterministicCriterionResultSchema",
  "eventSchema",
  "finalizeAcceptedResponseSchema",
  "finalizeCompletedStatusResponseSchema",
  "finalizeFailedStatusResponseSchema",
  "finalizeFailureErrorSchema",
  "finalizeInitialResponseSchema",
  "finalizeQueuedStatusResponseSchema",
  "finalizeRequestSchema",
  "finalizeResponseSchema",
  "finalizeRunningStatusResponseSchema",
  "finalizeStatusResponseSchema",
  "finalizeStatusUrlSchema",
  "formatGitHubAccessControlLabel",
  "githubAccessControlCatalogSchema",
  "githubAccessControlCategoryGroupSchema",
  "githubAccessControlCategorySchema",
  "githubAccessControlEndpointSchema",
  "githubAccessControlToolNames",
  "githubSeedStateSchema",
  "groupGitHubAccessControlByCategory",
  "hookEventSchema",
  "isLegacyEventRow",
  "isMultiTwinSeedEnvelope",
  "isUint64",
  "judgeModelSchema",
  "laneSchema",
  "llmCallEventSchema",
  "llmTurnEventSchema",
  "mapOtelSpanToEvent",
  "meResponseSchema",
  "msToNanos",
  "nanosToIso",
  "normalizeTaskVocabKeys",
  "otelAttributeValueSchema",
  "otelEventSchema",
  "otelSpanEventSchema",
  "otelSpanInputSchema",
  "otelSpanKindSchema",
  "otelStatusCodeSchema",
  "perTwinStateKeysSchema",
  "persistedScenarioSchema",
  "persistedTaskSchema",
  "planTierSchema",
  "probabilisticCriterionResultSchema",
  "projectAttributes",
  "providerScopedSeedStateSchema",
  "recorderEventSchema",
  "recorderFidelitySchema",
  "redactEvent",
  "redactSecrets",
  "runSchema",
  "scenarioConfigSchema",
  "scenarioSchema",
  "seedEnvelopeSchema",
  "seedStateSchema",
  "sessionPublicSchema",
  "sessionSchema",
  "sessionStateSchema",
  "shimLegacyEventToSpan",
  "shimmableLegacyEventSchema",
  "slackSeedStateSchema",
  "stateDeltaSchema",
  "stateUploadUrlEntrySchema",
  "stateUploadUrlResponseSchema",
  "stepSchema",
  "stripeSeedStateSchema",
  "subagentSpawnEventSchema",
  "submitResultRequestSchema",
  "submitResultResponseSchema",
  "summarizeGitHubAccessControlCatalog",
  "taskConfigSchema",
  "taskSchema",
  "teamInviteSchema",
  "teamMemberSchema",
  "teamRoleSchema",
  "teamSchema",
  "toolResultEventSchema",
  "toolUseEventSchema",
  "twinHttpEventSchema",
  "twinIdSchema",
  "unixNanoSchema",
  "usageResponseSchema",
  "userSchema",
  "w3cSpanIdSchema",
  "w3cTraceIdSchema",
] as const;

describe("@pome-sh/shared-types barrel export surface (F-754)", () => {
  it("re-exports exactly the pre-refactor runtime value surface", () => {
    expect(Object.keys(api).sort()).toEqual([...EXPECTED_EXPORTS]);
  });

  it("guards the TYPE surface (53 types/interfaces)", () => {
    // The real guard is the type-only import + _TypeSurfaceAssert tuple above,
    // enforced at typecheck time. This assertion just anchors the count at
    // runtime so the guard's scope is visible in test output.
    expect(TYPE_SURFACE_SIZE).toBe(53);
  });
});
