// SPDX-License-Identifier: Apache-2.0
import { describe, expect, it } from "vitest";
import { emitFidelityMarkdown } from "../src/fidelity.js";
import { toyTwin } from "./_toyTwin.js";

describe("emitFidelityMarkdown", () => {
  it("matches the expected snapshot for the toy twin", () => {
    const md = emitFidelityMarkdown(toyTwin, { lastVerified: "2026-05-09" });
    expect(md).toBe(`# toy Twin Fidelity

Auto-generated by \`@pome-sh/sdk\` for twin \`toy\` v0.1.0.

Last verified: 2026-05-09.

## MCP Tools

| Tool | Backing surface | Tier | Tests | Known deviations |
| --- | --- | --- | --- | --- |
| \`add_item\` | in-memory list | semantic | \`mcp-registry.test.ts\` | Items are unique only by insertion order, not by uniqueness constraint. |
| \`count_items\` | — | semantic | — | — |
`);
  });

  it("documents every declared tool", () => {
    const md = emitFidelityMarkdown(toyTwin);
    for (const tool of toyTwin.tools) {
      expect(md).toContain(`\`${tool.name}\``);
    }
  });

  it("falls back to manifest's default tier when tool fidelity.tier is unset", () => {
    const md = emitFidelityMarkdown(toyTwin);
    // count_items has no per-tool fidelity → should display "semantic" (manifest default)
    expect(md).toMatch(/\| `count_items` \| .* \| semantic \|/);
  });

  it("appends notes section when provided", () => {
    const md = emitFidelityMarkdown(toyTwin, { notes: "Hand-curated context here." });
    expect(md).toContain("## Notes\n\nHand-curated context here.");
  });
});
